config/routes.rb
Rails.application.routes.draw do

  resources :teams, only: [] do
    resources :players
  end

  resources :sports do
    resources :teams
  end


  get 'welcome/index'
  get 'welcome/about'
  get 'welcome/contact'

  #root 'welcome#index'
  #I could have used the above code to declare the default page the app loads when I navigate to the home page URL
  #but for pratice, I use the code below which does the same.
  root({to: 'welcome#index'})
end

app/models/player.rb
# == Schema Information
#
# Table name: players
#
#  id         :integer          not null, primary key
#  name       :string
#  number     :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Player < ActiveRecord::Base
  validates_presence_of :name
  validates_presence_of :number
  

end

app/models/sport.rb
# == Schema Information
#
# Table name: sports
#
#  id          :integer          not null, primary key
#  name        :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Sport < ActiveRecord::Base

  validates_presence_of :name
  validates_presence_of :description

  has_many :teams
end

app/models/team.rb
# == Schema Information
#
# Table name: teams
#
#  id          :integer          not null, primary key
#  name        :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  sport_id    :integer
#  player_id   :integer
#

class Team < ActiveRecord::Base
  validates_presence_of :name
  validates_presence_of :description
  validates_presence_of :sport_id

  belongs_to :sport
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
    @players = Player.all
  end

  def show
    @player = Player.find(params[:id])
  end

  def new
    @player = Player.new
  end

  def edit
    @player = Player.find(params[:id])
  end

  def update
    @player = Player.find(params[:id])
    @player.name = params[:player][:name]
    @player.number = params[:player][:number]
    @player.team_id = params[:player][:team_id]

    if @player.save
      flash[:notice] = "Player successfully updated"
      redirect_to @player
    else
      flash[:error] = "Player could not be saved"
      render :edit
    end
  end


  def create
    @player = Player.new
    @player.name = params[:player][:name]
    @player.number = params[:player][:number]
    @player.team_id = params[:player][:team_id]

    if @player.save
      flash[:notice] = "Player successfully saved."
      redirect_to "/players"
    else
      flash[:notice] = "Player could not be saved successgully"
      render :new
    end
  end

    def destroy
    @player = Player.find(params[:id])

    if @player.destroy
      flash[:notice] = "\"#{@player.name}\" was deleted successufully."
      redirect_to action: :index
    else
      flash.now[:alert] = "There was an error deleting the player."
      render :show
    end
  end
end

app/controllers/sports_controller.rb
class SportsController < ApplicationController
  def index
    @sports = Sport.all
  end

  def show
    @sport = Sport.find(params[:id])

  end

  def new
    @sport = Sport.new
  end

  def edit
    @sport = Sport.find(params[:id])
  end

  def update
    @sport = Sport.find(params[:id])
    @sport.name = params[:sport][:name]
    @sport.description = params[:sport][:description]
  

    if @sport.save
      flash[:notice] = "Sport successfully updated"
      redirect_to @sport
    else
      flash[:error] = "Sport could not be saved"
      render :edit
    end
  end

  def create

    @sport = Sport.new
    @sport.name = params[:sport][:name]
    @sport.description = params[:sport][:description]

    if @sport.save
      flash[:notice] = "Sport successfully saved."
      redirect_to "/sports"
    else
      flash[:error] = "Sport could not be saved"
      render :new
    end

  end


end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def index
    @teams = Team.all
  end

  def show
    @sport = Sport.find(params[:sport_id])
    @team = Team.find(params[:id])
  end

  def new
    @sport = Sport.find(params[:sport_id])
    @team = Team.new
  end

  def edit
    @sport = Sport.find(params[:sport_id])
    @team = Team.find(params[:id])
  end

  def create
    @team = Team.new
    @team.name = params[:team][:name]
    @team.description = params[:team][:description]
    @sport = Sport.find(params[:sport_id])
    @team.sport = @sport

    if @team.save
      flash[:notice] = "Team successfully saved."
      redirect_to @sport
    else
      flash[:error] ="Team could not be saved."
      render :new
    end
  end

  def update
    @team = Team.find(params[:id])
    @team.name = params[:team][:name]
    @team.description = params[:team][:description]
    @sport = Sport.find(params[:sport_id])

    if @team.save
      flash[:notice] = "Team successfully updated"
      redirect_to [@sport, @team]
    else
      flash[:error] = "Team could not be saved"
      render :edit
    end
  end

    def destroy
      @team = Team.find(params[:id])
      @sport = Sport.find(params[:sport_id])

      if @team.destroy
        flash[:notice] = "\"#{@team.name}\" was deleted successufully."
        redirect_to @sport
      else
        flash.now[:alert] = "There was an error deleting the team."
        render :show
      end
    end
  end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

  def form_group_tag(errors, &block)
    css_class = "form-group"
    css_class << " has-error" if errors.any?

    content_tag :div, capture(&block), class: css_class
    
  end

end

app/helpers/player_helper.rb
module PlayerHelper
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SportsGenerator</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
    <nav class="navbar">
      <ul class="nav navbar-nav">
        <% Sport.all.each do |s| %>
          <li><%= link_to s.name, s %>
          </li>
        <% end %>
      </ul>
    </nav>
    <% if flash[:notice] %>
      <div class="alert alert-info">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:error] %>
      <div class="alert alert-warning">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <%= flash[:error] %>
      </div>
    <% end %>
    <%= yield %>
  </div>

</body>
</html>

app/views/players/_form.html.erb
<%= form_for player do |f| %>
  <% if player.errors.any? %>
    <div class="alert alert-danger">
      <h4><%= pluralize(player.errors.count, "Error")%>.</h4>
      <ul>
        <% player.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<%= form_group_tag(player.errors[:name]) do %>
  <% f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
<% end %>

<%= form_group_tag(player.errors[:number]) do %>
  <%= f.label :number %>
  <%= f.text_area :number, class: 'form-control' %>
<% end %>

<%= form_group_tag(player.errors[:team_id]) do %>
  <%= f.label :team %>
  <%= f.select :team_id, Team.all.collect {|t| [t.name, t.id]} , {include_blank: true}, class: 'form-control' %>
<% end %>

  <div class="form-group">
    <%= f.submit "", class: "submit-button" %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>This is an edit page for Players</h1>

<%= render partial: "form", locals: {player: @player} %>

app/views/players/index.html.erb
<h1>Players list</h1>

<div class="col-md-8">
  <% @players.each do |p| %>
  <h3><%= link_to p.name, p %></h3>
  <p><%= p.number %></p>
  <% end %>
</div>
<div class="col-md-4">
  <%= link_to "create player", new_player_path, class:"btn btn-success" %>
</div>

app/views/players/new.html.erb
<h1>Create a new Player</h1>

<%= render partial: "form", locals: {player: @player} %>

app/views/players/show.html.erb
<h1><%= @player.name %></h1>

<div class="col-md-8">
  <p><%= @player.number %></p>
</div>

<div class="col-md-4">
  <%= link_to "edit player", edit_player_path(@player), class:"btn btn-success" %>
  <%= link_to "delete player", player_path(@player), method: :delete, class:"btn btn-success" %>
</div>

app/views/sports/_form.html.erb
<%= form_for sport do |f| %>
  <% if sport.errors.any? %>
    <div class="alert alert-danger">
      <h4><%= pluralize(sport.errors.count, "Error")%>. </h4>
      <ul>
        <% sport.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_group_tag(sport.errors[:name]) do %>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  <% end %>

  <%= form_group_tag(sport.errors[:description]) do %>
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  <% end %>

  <div class="form-group">
    <%= f.submit "", class: "submit-button" %>
  </div>

<% end %>

app/views/sports/edit.html.erb
<h1>This is an edit page</h1>

<%= render partial: "form", locals: {sport: @sport} %>

app/views/sports/index.html.erb
<h1>Sports list</h1>

<div class="col-md-8">
  <% @sports.each do |s| %>
    <h3><%= link_to s.name, s %></h3>
    <p><%= s.description %></p>
  <% end %>
</div>
<div class="col-md-4">
  <%= link_to "create sport", new_sport_path, class:"btn btn-success" %>
</div>

app/views/sports/new.html.erb
<h1>Create a new sport.</h1>


<%= render partial: "form", locals: {sport: @sport} %>

app/views/sports/show.html.erb
<h1><%= @sport.name %></h1>

<div class="col-md-8">
  <p><% @sport.description %></p>
  <% @sport.teams.each do |t| %>
    <h3><%= link_to t.name, sport_team_path(@sport, t) %></h3>
    <p><%= t.name %></p>
  <% end %>
</div>

<div class="col-md-4">
  <%= link_to "edit sport", edit_sport_path(@sport), class:"btn btn-success" %>
  <%= link_to "delete sport", sport_path(@sport), method: :delete, class:"btn btn-success " %>
  <%= link_to "create team", new_sport_team_path(@sport), class: "btn btn-success" %>
</div>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>